import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'language_provider.dart';

class AppStrings {
  static const _en = {
    // --- Common ---
    'search': 'Search',
    'search_customers': 'Search customers...',
    'search_products_hint': 'Search products, brands, models...',
    'search_projects_hint': 'Search projects, customers, responsible...',
    'search_users_hint': 'Search users...',
    'search_quotations_hint': 'Search quotations...',
    'search_invoices_hint': 'Search invoices...',
    'search_payments_hint': 'Search payments...',
    'search_activity_hint': 'Search activities...',
    'search_hint': 'Search customers, projects...',
    'search_query_hint': 'Type at least 2 characters to search',
    'no_results': 'No results found',
    'add_new': 'Add New',
    'edit': 'Edit',
    'delete': 'Delete',
    'delete_all': 'Delete All',
    'save': 'Save',
    'saving': 'Saving...',
    'cancel': 'Cancel',
    'close': 'Close',
    'back': 'Back',
    'project_overview': 'Project Overview',
    'project_parameters': 'Project Parameters',
    'project_lifecycle': 'Project Lifecycle',
    'capacity': 'Capacity',
    'kw_unit': 'kW',
    'create': 'Create',
    'add': 'Add',
    'refresh': 'Refresh',
    'refreshing_data': 'Refreshing data...',
    'retry': 'Retry',
    'actions': 'Actions',
    'action': 'Action',
    'details': 'Details',
    'performed_by': 'Performed By',
    'reference': 'Reference',
    'activity_details': 'Activity Details',
    'view_reference': 'View Reference',
    'items_summary': 'Items Summary',
    'time': 'Time',
    'loading': 'Loading...',
    'error': 'An error occurred',
    'no_data': 'No data found',
    'date_format': 'dd MMM, yy',
    'full_date_format': 'dd MMMM, yyyy',
    'time_format': 'hh:mm a',
    'date_time_format': 'dd MMM, HH:mm',
    'view_all': 'View All',
    'view_details': 'View Details',
    'today': 'Today',
    'date': 'Date',
    'select_date': 'Select Date',
    'status': 'Status',
    'type': 'Type',
    'name': 'Name',
    'phone': 'Phone',
    'phone2': 'Secondary Phone',
    'email': 'Email',
    'address': 'Address',
    'notes': 'Notes',
    'add_note': 'Add Note',
    'edit_notes': 'Edit Notes',
    'no_notes': 'No notes recorded.',
    'governorate': 'Governorate',
    'city': 'City',
    'location': 'Location',
    'no_location_data': 'No location data available',
    'total': 'Total',
    'calculate_label': 'Calculate',
    'unknown': 'Unknown',
    'user_default': 'User',
    'vs_last_month': 'vs last month',
    'click_to_sort': 'Click to sort',
    'mark_all_read': 'Mark all read',
    'clear_all': 'Clear All',
    'clear_all_confirm': 'Are you sure you want to delete all notifications?',
    'unassigned': 'Unassigned',
    'all_statuses': 'All Statuses',
    'clear_filters': 'Clear Filters',
    'pdf': 'PDF',
    'open_pdf': 'Open PDF',
    'print': 'Print',
    'excel': 'Excel',
    'import_data': 'Import Data',
    'import_success': 'Data imported successfully!',
    'import_error': 'Failed to import data.',
    'export_data': 'Export Data',
    'export_success': 'Data exported successfully!',
    'export_error': 'Failed to export data.',
    'users': 'Users',
    'customers': 'Customers',
    'projects': 'Projects',
    'quotations': 'Quotations',
    'quotation': 'Quotation',
    'report_approved_quotes': 'Approved Quotes',
    'report_invoiced': 'Invoiced',
    'report_collected': 'Collected',
    'report_outstanding': 'Outstanding',
    'report_cash_margin': 'Cash Margin',
    'reports': 'Reports',
    'analytics_dashboard': 'Analytics Dashboard',
    'business_metrics_desc': 'Real-time business performance metrics',
    'filter_range': 'Filter Range',
    'financial_overview': 'Financial Overview',
    'financial_overview_desc': 'Invoiced vs Collected vs Margin',
    'projects_by_status_desc': 'Distribution of current projects',
    'monthly_performance': 'Monthly Performance Trends',
    'monthly_performance_desc': 'Tracking revenue and collections over time',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'from': 'From',
    'to': 'To',
    'apply_filter': 'Apply Filter',
    'reset_filters': 'Reset Filters',
    'payments': 'Payments',
    'price_list': 'Price List',
    'products': 'Products & Price List',
    'product': 'Product',
    'all_categories': 'All Categories',
    'price': 'Price',
    'item': 'Item',
    'unit': 'Unit',
    'cost': 'Cost',
    'selling': 'Selling',
    'invoices': 'Invoices & Payments',
    'sales': 'Sales',
    'operations': 'Operations',
    'management': 'Management',
    'profile_settings': 'Profile & Settings',
    'appearance': 'Appearance',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'operations_desc': 'Suppliers, inventory and purchase orders.',
    'overview': 'Overview',
    'sync_data': 'Sync Data',
    'analytics': 'Analytics',
    'recent_activity': 'Recent Activity',
    'project_pipeline': 'Project Pipeline',
    'distribution_by_status': 'Current distribution by status',
    'customer_geography': 'Customer Geography',
    'customers_by_gov': 'Customers by governorate',
    'recent_customers': 'Recent Customers',
    'recent_projects': 'Recent Projects',
    'total_value': 'Total Value',
    'quotation_value': 'Quotation Value',
    'unnamed_customer': 'Unnamed Customer',
    'no_phone': 'No phone number',
    'dashboard_error': 'Dashboard could not load',
    'try_again': 'Try again',
    'kpi_total_customers': 'Total Customers',
    'kpi_projects': 'Projects',
    'kpi_portfolio_value': 'Portfolio Value',
    'kpi_installed_capacity': 'Installed Capacity',
    'suppliers': 'Suppliers',
    'suppliers_list': 'Suppliers List',
    'supplier': 'Supplier',
    'supplier_info': 'Supplier Information',
    'inventory': 'Inventory',
    'purchase_orders': 'Purchase Orders',
    'purchase_orders_list': 'Purchase Orders List',
    'order_items': 'Order Items',
    'add_item': 'Add Item',
    'qty': 'Qty',
    'no_items_added_yet': 'No items added yet',
    'add_supplier': 'Add Supplier',
    'no_suppliers': 'No Suppliers',
    'no_purchase_orders': 'No Purchase Orders',
    'no_items': 'No Items Found',
    'try_adjusting_search': 'Try adjusting your search query',
    'new_purchase_order': 'New Purchase Order',
    'adjust_stock': 'Adjust Stock',
    'stock_history': 'Stock History',
    'on_hand': 'On hand',
    'reorder_level': 'Reorder',
    'increase_stock': 'Increase stock',
    'decrease_stock': 'Decrease stock',
    'no_movements_recorded': 'No stock movements recorded for this item.',
    'new_invoice': 'New Invoice',
    'record_payment': 'Record Payment',
    'add_interaction': 'Add Interaction',
    'add_follow_up': 'Add Follow-up',
    'add_quotation': 'Add Quotation',
    'scheduled': 'Scheduled',
    'interaction_history': 'Interaction History',
    'no_follow_ups': 'No follow-ups yet.',
    'no_interactions': 'No interactions yet.',
    'no_activities': 'No activities found',
    'activities': 'Activities',
    'amount': 'Amount',
    'remaining': 'Remaining',
    'tax_amount': 'Tax amount',
    'invoice_item': 'Invoice item',
    'customer_id': 'Customer ID',
    'description': 'Description',
    'payment_method': 'Payment Method',
    'all_methods': 'All Methods',
    'po_draft': 'Draft',
    'po_ordered': 'Ordered',
    'po_partially_received': 'Partially Received',
    'po_received': 'Received',
    'po_cancelled': 'Cancelled',
    'all_roles': 'All Roles',
    'please_add_customer': 'Please add at least one customer first.',
    'reset_password': 'Reset Password',
    'enable': 'Enable',
    'disable': 'Disable',
    'add_product': 'Add Product',
    'edit_product': 'Edit Product',
    'pricing': 'Pricing',
    'specifications': 'Specifications',
    'brand': 'Brand',
    'model': 'Model',
    'specification': 'Specification',
    'country_of_origin': 'Country of Origin',
    'cost_price': 'Cost Price',
    'selling_price': 'Selling Price',
    'code': 'Code',
    'contact_person': 'Contact Person',
    'tax_number': 'Tax Number',
    'select_category': 'Select Category',
    'enter_valid_amount': 'Please enter a valid amount',

    // --- Auth ---
    'sign_in': 'Sign In',
    'sign_in_subtitle': 'Sign in to manage solar projects',
    'username': 'Username',
    'username_hint': 'Enter your username',
    'password': 'Password',
    'password_hint': 'Enter your password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'no_account': "Don't have an account? ",
    'contact_admin': 'Contact Administrator',
    'welcome_back': 'RSGS Portal',
    'please_contact_admin_reset': 'Please contact your system administrator to reset your password.',
    'required': 'Required',
    'invalid_phone': 'Phone must be 11 digits',
    'invalid_credentials': 'Invalid credentials',
    'enter_credentials': 'Please enter username and password',
    'error_email_client': 'Could not open email client',
    'logout': 'Logout',
    'admin': 'Administrator',
    'engineer': 'Engineer',
    'profile': 'Profile',
    'user': 'User',

    // --- Dashboard ---
    'dashboard': 'Dashboard',
    'total_customers': 'Total Customers',
    'total_projects': 'Total Projects',
    'finished_projects': 'Completed Projects',
    'total_revenue': 'Total Revenue',
    'revenue': 'Revenue',
    'active_projects': 'Active Projects',
    'customer_base': 'Customer Base',
    'solar_capacity': 'Solar Capacity',
    'projects_in_portfolio': 'projects in portfolio',
    'completed': 'Completed',
    'relationships_crm': 'Relationships in your CRM',
    'across_all_projects': 'Across all recorded projects',
    'pipeline_subtitle': 'A live view of work across every stage',
    'view_projects': 'View projects',
    'recently_added_projects': 'Recently added projects',
    'projects_subtitle': 'The latest work created in your workspace',
    'coming_up': 'Coming up',
    'coming_up_subtitle': 'Your next appointments and follow-ups',
    'schedule_clear': 'Your schedule is clear.',
    'no_projects_yet_desc': 'No projects yet — create your first one to see it here.',
    'good_morning': 'Good Morning',
    'good_afternoon': 'Good Afternoon',
    'good_evening': 'Good Evening',
    'new_lead': 'New Lead',
    'quick_actions': 'Quick Actions',
    'env_impact': 'Environmental Impact',
    'co2_saved': 'CO2 Offset',
    'trees_saved': 'Equivalent Trees',
    'ton_co2': 'Tons of CO2',
    'trees_count': 'Trees planted',
    'revenue_by_gov': 'Revenue by Governorate',
    'project_health': 'Project Health',
    'avg_project_value': 'Avg Project Value',
    'projects_this_month': 'Projects This Month',
    'energy_saved': 'Energy Saved',
    'kwh': 'kWh',
    'tasks_due_today': 'Tasks due today',
    'active_projects_count': 'Active projects',
    'share_impact': 'Share Impact',
    'view_reports': 'View Reports',
    'engineer_performance': 'Engineer Performance',
    'projects_count_by_engineer': 'Projects distribution by engineer',
    'co2_saved_yearly': 'CO2 saved yearly',
    'trees_equivalent': 'Equivalent trees',
    'no_recent_activity': 'No recent activity found',
    'customers_in_system': 'Customers in system',
    'estimated_valuation': 'Estimated valuation',
    'solar_capacity_recorded': 'Solar capacity recorded',

    // --- Quotation Form ---
    'edit_quotation': 'Edit Quotation',
    'new_quotation': 'New Quotation',
    'quotation_details': 'Quotation Details',
    'previous': 'Previous',
    'next_step': 'Next Step',
    'update_quotation': 'Update Quotation',
    'create_quotation': 'Create Quotation',
    'view_summary': 'View Summary',
    'estimated_total': 'Estimated Total',
    'quotation_summary': 'Quotation Summary',
    'subtotal_items_addons': 'Subtotal (Items & Add-ons)',
    'profit_margin': 'Profit Margin',
    'discount': 'Discount',
    'tax': 'Tax',
    'total_price': 'Total Price',
    'internal_cost': 'Internal Cost',
    'client_context': 'Client & Context',
    'assign_customer_project': 'Assign customer and project details',
    'system_topology': 'System Topology',
    'select_topology': 'Select the system topology for this quotation',
    'topology_selection': 'Topology Selection',
    'system_parameters': 'System Parameters',
    'system_description': 'System Description',
    'system_capacity_required': 'System Capacity *',
    'capacity_unit': 'Capacity Unit',
    'quotation_date': 'Quotation Date',
    'valid_until': 'Valid Until',
    'lifecycle_dates': 'Lifecycle Dates',
    'bill_of_materials': 'Bill of Materials',
    'required_components': 'Required components for',
    'add_custom_item': 'Add Custom Item',
    'internal_pricing': 'Internal Pricing',
    'costs_margins_taxes': 'Costs, margins and taxes',
    'direct_costs_addons': 'Direct Costs & Add-ons',
    'additional_materials': 'Additional Materials',
    'transportation': 'Transportation',
    'installation': 'Installation',
    'other_cost': 'Other Cost',
    'pricing_logic': 'Pricing Logic',
    'document_content': 'Document Content',
    'official_text_pdf': 'Official text for the PDF document',
    'document_drafting': 'Document Drafting',
    'introduction': 'Introduction',
    'general_terms': 'General Terms',
    'terms_and_conditions': 'Terms & Conditions',
    'payment_terms': 'Payment Terms',
    'item_details': 'Item Details',
    'item_name_required': 'Item Name *',
    'origin': 'Origin',
    'internal_notes_optional': 'Internal Notes (Optional)',
    'product_component_catalog': 'Product / Component Catalog',
    'manual_item_no_catalog': 'Manual item — no catalog product',
    'select_customer_first': 'Select customer first',
    'no_projects_for_customer': 'No projects for this customer',
    'loading_customers': 'Loading customers...',
    'failed_load_customers': 'Failed to load customers',
    'loading_projects': 'Loading projects...',
    'failed_load_projects': 'Failed to load projects',
    'customer_required': 'Customer is required',
    'capacity_required': 'Capacity is required',
    'please_select_customer': 'Please select a customer',
    'enter_valid_capacity': 'Please enter a valid system capacity',
    'add_at_least_one_item': 'Please add at least one item to the quotation',
    'items_must_have_name': 'All items must have a name',
    'item_must_have_qty': 'must have a quantity > 0',
    'margin_range_error': 'Profit Margin must be between 0 and 100%',
    'tax_range_error': 'Tax must be between 0 and 100%',
    'missing_required_categories': 'Missing required categories',
    'quotation_created_success': 'Quotation created successfully',
    'quotation_updated_success': 'Quotation updated successfully',
    'failed_load_quotation': 'Failed to load quotation',
    'quotation_not_found': 'Quotation not found',
    'no_quotations_found': 'No quotations found',
    'all_types': 'All Types',

    // --- Statuses & Channels ---
    'Draft': 'Draft',
    'Pending': 'Pending',
    'Approved': 'Approved',
    'Sent': 'Sent',
    'Rejected': 'Rejected',
    'Expired': 'Expired',
    'In Progress': 'In Progress',
    'Completed': 'Completed',
    'Cancelled': 'Cancelled',
    'Facebook': 'Facebook',
    'WhatsApp': 'WhatsApp',
    'Website': 'Website',
    'Referral': 'Referral',
    'Call': 'Call',
    'Walk-in': 'Walk-in',
    'Exhibition': 'Exhibition',
    'Other': 'Other',
    'Organic Lead': 'Organic Lead',
    'Won': 'Won',
    'Lost': 'Lost',
    'Negotiation': 'Negotiation',
    'Quotation Sent': 'Proposal Sent',
    'Contacted': 'Contacted',
    'Visited': 'Visited',
    'New': 'New',
    'Deferred': 'Deferred',
    'On-Grid': 'On-Grid',
    'Off-Grid': 'Off-Grid',
    'Solar Pump': 'Solar Pump',

    // --- Governorates ---
    'Cairo': 'Cairo',
    'Alexandria': 'Alexandria',
    'Giza': 'Giza',
    'Red Sea': 'Red Sea',
    'South Sinai': 'South Sinai',
    'North Sinai': 'North Sinai',
    'Port Said': 'Port Said',
    'Suez': 'Suez',
    'Luxor': 'Luxor',
    'Aswan': 'Aswan',
    'Qena': 'Qena',
    'Sohag': 'Sohag',
    'Assiut': 'Assiut',
    'Minya': 'Minya',
    'Beni Suef': 'Beni Suef',
    'Fayoum': 'Fayoum',
    'Dakahlia': 'Dakahlia',
    'Sharqia': 'Sharqia',
    'Qalyubia': 'Qalyubia',
    'Kafr El Sheikh': 'Kafr El Sheikh',
    'Gharbia': 'Gharbia',
    'Monufia': 'Monufia',
    'Beheira': 'Beheira',
    'Ismailia': 'Ismailia',
    'Damietta': 'Damietta',
    'Matrouh': 'Matrouh',
    'New Valley': 'New Valley',

    // --- Batch 2 ---
    'all_channels': 'All Channels',
    'unknown_user': 'Unknown User',
    'reset': 'Reset',
    'filter': 'Filter',
    'filter_customers': 'Filter Customers',
    'apply_filters': 'Apply Filters',
    'interaction_tracking': 'Interaction Tracking',
    'first_contact': 'First Contact',
    'final_contact': 'Final Contact',
    'comment': 'Comment',
    'whatsapp': 'WhatsApp',
    'email_item': 'Email',
    'note': 'Note',
    'visit': 'Visit',
    'filter_projects': 'Filter Projects',
    'total_kw': 'Total kW',
    'min': 'Min',
    'max': 'Max',
    'active_only': 'Active only',
    'add_user': 'Add User',
    'edit_user': 'Edit User',
    'account_settings': 'Account Settings',
    'full_name': 'Full Name',
    'invalid_email': 'Invalid email',
    'role': 'Role',
    'select_role': 'Select Role',
    'new_password_label': 'New password',
    'confirm_password_label': 'Confirm password',
    'solar_panels': 'Solar Panels',
    'mounting_structure': 'Mounting Structure',
    'inverter': 'Inverter',
    'dc_cables': 'DC Cables',
    'dc_combiner': 'DC Combiner',
    'cable_tray': 'Cable Tray',
    'grounding_system': 'Grounding System',
    'maintenance': 'Maintenance',
    'batteries': 'Batteries',
    'inverter_panel': 'Inverter Panel',
    'cable_pipes': 'Cable Pipes',
    'topology': 'Topology',
    'no_users_found': 'No users found',
    'pcs': 'pcs',
    'installation_item': 'Installation',
    'transportation_item': 'Transportation',
    'active': 'Active',
    'disabled': 'Disabled',
    'inactive': 'Inactive',
    'history': 'History',
    'adjust': 'Adjust',
    'solar_invoice_desc': 'Solar project invoice',
    'select_gov': 'Select Governorate',
    'select_channel': 'Select Channel',
    'select_status': 'Select Status',
    'reset_password_for': 'Reset password — ',
    'min_12_chars': 'Minimum 12 characters.',
    'passwords_no_match': 'Passwords do not match.',
    'new_password': 'New password',
    'confirm_password': 'Confirm password',
    'basic_info': 'Basic Info',
    'task': 'Task',
    'meeting': 'Meeting',
    'follow_up': 'Follow-up',
    'installation_event': 'Installation',
    'events': 'Events',
    'dates': 'Dates',
  };

  static const _ar = {
    // --- Common ---
    'search': 'بحث',
    'search_customers': 'ابحث عن العملاء...',
    'search_products_hint': 'ابحث عن المنتجات، العلامات التجارية، الموديلات...',
    'search_projects_hint': 'ابحث عن المشاريع، العملاء، المسؤولين...',
    'search_users_hint': 'ابحث عن المستخدمين...',
    'search_quotations_hint': 'ابحث عن عروض الأسعار...',
    'search_invoices_hint': 'ابحث عن الفواتير...',
    'search_payments_hint': 'ابحث عن المدفوعات...',
    'search_activity_hint': 'ابحث عن الأنشطة...',
    'search_hint': 'ابحث عن العملاء، المشاريع...',
    'search_query_hint': 'اكتب حرفين على الأقل للبحث',
    'no_results': 'لم يتم العثور على نتائج',
    'add_new': 'إضافة جديد',
    'edit': 'تعديل',
    'delete': 'حذف',
    'delete_all': 'حذف الكل',
    'save': 'حفظ',
    'saving': 'جاري الحفظ...',
    'cancel': 'إلغاء',
    'close': 'إغلاق',
    'back': 'رجوع',
    'project_overview': 'نظرة عامة على المشروع',
    'project_parameters': 'مواصفات المشروع',
    'project_lifecycle': 'دورة حياة المشروع',
    'capacity': 'القدرة',
    'kw_unit': 'كيلوواط',
    'create': 'إنشاء',
    'add': 'إضافة',
    'refresh': 'تحديث',
    'refreshing_data': 'جاري تحديث البيانات...',
    'retry': 'إعادة المحاولة',
    'actions': 'الإجراءات',
    'action': 'الإجراء',
    'details': 'التفاصيل',
    'performed_by': 'بواسطة',
    'reference': 'المرجع',
    'activity_details': 'تفاصيل النشاط',
    'view_reference': 'عرض المرجع',
    'items_summary': 'ملخص البنود',
    'time': 'الوقت',
    'loading': 'جاري التحميل...',
    'error': 'حدث خطأ ما',
    'no_data': 'لا توجد بيانات',
    'date_format': 'dd / MM / yyyy',
    'full_date_format': 'dd / MM / yyyy',
    'time_format': 'HH:mm',
    'date_time_format': 'dd / MM / yyyy, HH:mm',
    'view_all': 'عرض الكل',
    'view_details': 'عرض التفاصيل',
    'today': 'اليوم',
    'date': 'التاريخ',
    'select_date': 'اختر التاريخ',
    'status': 'الحالة',
    'type': 'النوع',
    'name': 'الاسم',
    'phone': 'رقم التواصل',
    'phone2': 'رقم تواصل إضافي',
    'email': 'البريد الإلكتروني',
    'address': 'العنوان',
    'notes': 'ملاحظات',
    'add_note': 'إضافة ملاحظة',
    'edit_notes': 'تعديل الملاحظات',
    'no_notes': 'لا توجد ملاحظات مسجلة.',
    'governorate': 'المحافظة',
    'city': 'المدينة',
    'location': 'الموقع',
    'no_location_data': 'لا توجد بيانات للموقع',
    'total': 'الإجمالي',
    'calculate_label': 'حساب',
    'unknown': 'غير معروف',
    'user_default': 'مستخدم',
    'vs_last_month': 'مقارنة بالشهر الماضي',
    'click_to_sort': 'اضغط للترتيب',
    'mark_all_read': 'تحديد الكل كمقروء',
    'clear_all': 'مسح الكل',
    'clear_all_confirm': 'هل أنت متأكد من رغبتك في حذف جميع الإشعارات؟',
    'unassigned': 'غير محدد',
    'all_statuses': 'كل الحالات',
    'clear_filters': 'مسح الفلاتر',
    'pdf': 'بي دي إف',
    'open_pdf': 'فتح PDF',
    'print': 'طباعة',
    'excel': 'إكسل',
    'import_data': 'استيراد بيانات',
    'import_success': 'تم استيراد البيانات بنجاح!',
    'import_error': 'فشل استيراد البيانات.',
    'export_data': 'تصدير بيانات',
    'export_success': 'تم تصدير البيانات بنجاح!',
    'export_error': 'فشل تصدير البيانات.',
    'users': 'المستخدمون',
    'customers': 'العملاء',
    'projects': 'المشاريع',
    'quotations': 'عروض الأسعار',
    'quotation': 'عرض سعر',
    'report_approved_quotes': 'عروض مقبولة',
    'report_invoiced': 'إجمالي الفواتير',
    'report_collected': 'إجمالي التحصيل',
    'report_outstanding': 'مبالغ متبقية',
    'report_cash_margin': 'الهامش النقدي',
    'reports': 'التقارير',
    'analytics_dashboard': 'لوحة التحليلات',
    'business_metrics_desc': 'مؤشرات أداء الأعمال في الوقت الفعلي',
    'filter_range': 'نطاق التصفية',
    'financial_overview': 'نظرة مالية عامة',
    'financial_overview_desc': 'مقارنة الفواتير والتحصيل والهامش',
    'projects_by_status_desc': 'توزيع المشاريع الحالية حسب الحالة',
    'monthly_performance': 'اتجاهات الأداء الشهري',
    'monthly_performance_desc': 'تتبع الإيرادات والتحصيلات بمرور الوقت',
    'start_date': 'تاريخ البدء',
    'end_date': 'تاريخ الانتهاء',
    'from': 'من',
    'to': 'إلى',
    'apply_filter': 'تطبيق الفلتر',
    'reset_filters': 'إعادة تعيين الفلاتر',
    'payments': 'المدفوعات',
    'price_list': 'قائمة الأسعار',
    'products': 'المنتجات وقائمة الأسعار',
    'product': 'المنتج',
    'all_categories': 'كل التصنيفات',
    'price': 'السعر',
    'item': 'البند',
    'unit': 'الوحدة',
    'cost': 'التكلفة',
    'selling': 'سعر البيع',
    'invoices': 'الفواتير والمدفوعات',
    'sales': 'المبيعات',
    'operations': 'التشغيل',
    'management': 'الإدارة',
    'profile_settings': 'الملف الشخصي والإعدادات',
    'appearance': 'المظهر',
    'light_mode': 'الوضع الفاتح',
    'dark_mode': 'الوضع الداكن',
    'operations_desc': 'الموردين، المخزون وأوامر الشراء.',
    'overview': 'نظرة عامة',
    'sync_data': 'تزامن البيانات',
    'analytics': 'التحليلات',
    'recent_activity': 'النشاط الأخير',
    'project_pipeline': 'مخطط المشاريع',
    'distribution_by_status': 'التوزيع الحالي حسب الحالة',
    'customer_geography': 'جغرافيا العملاء',
    'customers_by_gov': 'العملاء حسب المحافظة',
    'recent_customers': 'العملاء الجدد',
    'recent_projects': 'المشاريع الحديثة',
    'total_value': 'القيمة الإجمالية',
    'quotation_value': 'قيمة عروض الأسعار',
    'unnamed_customer': 'عميل بدون اسم',
    'no_phone': 'لا يوجد رقم هاتف',
    'dashboard_error': 'فشل تحميل لوحة القيادة',
    'try_again': 'إعادة المحاولة',
    'kpi_total_customers': 'إجمالي العملاء',
    'kpi_projects': 'المشاريع',
    'kpi_portfolio_value': 'قيمة المحفظة',
    'kpi_installed_capacity': 'القدرة المركبة',
    'suppliers': 'الموردين',
    'suppliers_list': 'قائمة الموردين',
    'inventory': 'المخزون',
    'order_items': 'بنود الطلب',
    'add_item': 'إضافة بند',
    'qty': 'الكمية',
    'no_items_added_yet': 'لم يتم إضافة بنود بعد',
    'purchase_orders': 'أوامر الشراء',
    'purchase_orders_list': 'قائمة أوامر الشراء',
    'add_supplier': 'إضافة مورد',
    'no_suppliers': 'لا يوجد موردين',
    'no_purchase_orders': 'لا يوجد أوامر شراء',
    'no_items': 'لا يوجد أصناف',
    'try_adjusting_search': 'حاول تغيير كلمة البحث',
    'new_purchase_order': 'أمر شراء جديد',
    'adjust_stock': 'تعديل المخزون',
    'stock_history': 'سجل المخزون',
    'on_hand': 'متوفر',
    'reorder_level': 'إعادة الطلب',
    'increase_stock': 'زيادة المخزون',
    'decrease_stock': 'تقليل المخزون',
    'no_movements_recorded': 'لا توجد حركات مخزنية مسجلة لهذا الصنف.',
    'new_invoice': 'فاتورة جديدة',
    'record_payment': 'تسجيل دفعة',
    'add_interaction': 'إضافة تفاعل',
    'add_follow_up': 'إضافة متابعة',
    'add_quotation': 'إضافة عرض أسعار',
    'scheduled': 'مجدولة',
    'interaction_history': 'سجل التفاعلات',
    'no_follow_ups': 'لا توجد متابعات بعد.',
    'no_interactions': 'لا توجد تفاعلات بعد.',
    'no_activities': 'لا توجد أنشطة',
    'activities': 'الأنشطة',
    'amount': 'المبلغ',
    'remaining': 'المتبقي',
    'tax_amount': 'قيمة الضريبة',
    'invoice_item': 'بند الفاتورة',
    'customer_id': 'معرف العميل',
    'description': 'الوصف',
    'payment_method': 'طريقة الدفع',
    'all_methods': 'جميع الطرق',
    'po_draft': 'مسودة',
    'po_ordered': 'تم الطلب',
    'po_partially_received': 'مستلم جزئياً',
    'po_received': 'مستلم',
    'po_cancelled': 'ملغي',
    'all_roles': 'كل الأدوار',
    'please_add_customer': 'يرجى إضافة عميل واحد على الأقل أولاً.',
    'reset_password': 'إعادة تعيين كلمة المرور',
    'enable': 'تفعيل',
    'disable': 'تعطيل',
    'add_product': 'إضافة منتج',
    'edit_product': 'تعديل منتج',
    'pricing': 'التسعير',
    'specifications': 'المواصفات',
    'brand': 'العلامة التجارية',
    'model': 'الموديل',
    'specification': 'المواصفات الفنية',
    'country_of_origin': 'بلد المنشأ',
    'cost_price': 'سعر التكلفة',
    'selling_price': 'سعر البيع',
    'code': 'الكود',
    'contact_person': 'مسؤول التواصل',
    'tax_number': 'الرقم الضريبي',
    'select_category': 'اختر التصنيف',
    'enter_valid_amount': 'يرجى إدخال مبلغ صحيح',

    // --- Auth ---
    'sign_in': 'تسجيل الدخول',
    'sign_in_subtitle': 'سجل الدخول لإدارة مشاريع الطاقة الشمسية',
    'username': 'اسم المستخدم',
    'username_hint': 'أدخل اسم المستخدم',
    'password': 'كلمة المرور',
    'password_hint': 'أدخل كلمة المرور',
    'remember_me': 'تذكرني',
    'forgot_password': 'نسيت كلمة المرور؟',
    'no_account': 'ليس لديك حساب؟ ',
    'contact_admin': 'اتصل بمسؤول النظام',
    'welcome_back': 'بوابة RSGS',
    'please_contact_admin_reset': 'يرجى الاتصال بمسؤول النظام لإعادة تعيين كلمة المرور الخاصة بك.',
    'required': 'مطلوب',
    'invalid_phone': 'يجب أن يكون الرقم ١١ خانة',
    'invalid_credentials': 'بيانات الاعتماد غير صالحة',
    'enter_credentials': 'يرجى إدخل اسم المستخدم وكلمة المرور',
    'error_email_client': 'تعذر فتح تطبيق البريد الإلكتروني',
    'logout': 'تسجيل الخروج',
    'admin': 'مدير النظام',
    'engineer': 'مهندس / مسؤول',
    'profile': 'الملف الشخصي',
    'user': 'مستخدم',

    // --- Dashboard ---
    'dashboard': 'لوحة القيادة',
    'total_customers': 'إجمالي العملاء',
    'total_projects': 'إجمالي المشاريع',
    'finished_projects': 'المشاريع المكتملة',
    'total_revenue': 'إجمالي الإيرادات',
    'revenue': 'الإيرادات',
    'active_projects': 'المشاريع النشطة',
    'customer_base': 'قاعدة العملاء',
    'solar_capacity': 'القدرة الشمسية',
    'projects_in_portfolio': 'مشاريع في المحفظة',
    'completed': 'مكتمل',
    'relationships_crm': 'علاقة في نظامك',
    'across_all_projects': 'عبر جميع المشاريع المسجلة',
    'pipeline_subtitle': 'عرض حي للعمل عبر جميع المراحل',
    'view_projects': 'عرض المشاريع',
    'recently_added_projects': 'المشاريع المضافة حديثاً',
    'projects_subtitle': 'أحدث الأعمال التي تم إنشاؤها',
    'coming_up': 'قادم قريباً',
    'coming_up_subtitle': 'مواعيدك ومتابعاتك القادمة',
    'schedule_clear': 'جدولك خالٍ حالياً.',
    'no_projects_yet_desc': 'لا توجد مشاريع بعد - قم بإنشاء أول مشروع لرؤيته هنا.',
    'good_morning': 'صباح الخير',
    'good_afternoon': 'مساء الخير',
    'good_evening': 'مساء الخير',
    'new_lead': 'طلب جديد',
    'quick_actions': 'إجراءات سريعة',
    'env_impact': 'الأثر البيئي',
    'co2_saved': 'توفير الكربون',
    'trees_saved': 'ما يعادل الأشجار',
    'ton_co2': 'طناً من الكربون',
    'trees_count': 'شجرة مزروعة',
    'revenue_by_gov': 'الإيرادات حسب المحافظة',
    'project_health': 'حالة المشاريع',
    'avg_project_value': 'متوسط قيمة المشروع',
    'projects_this_month': 'مشاريع هذا الشهر',
    'energy_saved': 'الطاقة الموفرة',
    'kwh': 'كيلوواط ساعة',
    'tasks_due_today': 'مهام مستحقة اليوم',
    'active_projects_count': 'مشروعاً نشطاً',
    'share_impact': 'مشاركة الأثر',
    'view_reports': 'عرض التقارير',
    'engineer_performance': 'أداء المهندسين',
    'projects_count_by_engineer': 'توزيع المشاريع حسب المهندس',
    'co2_saved_yearly': 'توفير الكربون سنوياً',
    'trees_equivalent': 'ما يعادل الأشجار',
    'no_recent_activity': 'لا يوجد نشاط حديث',
    'customers_in_system': 'عميل في النظام',
    'estimated_valuation': 'تقييم تقديري',
    'solar_capacity_recorded': 'القدرة الشمسية المسجلة',

    // --- Quotation Form ---
    'edit_quotation': 'تعديل عرض الأسعار',
    'new_quotation': 'عرض أسعار جديد',
    'quotation_details': 'تفاصيل عرض السعر',
    'previous': 'السابق',
    'next_step': 'الخطوة التالية',
    'update_quotation': 'تحديث العرض',
    'create_quotation': 'إنشاء عرض السعر',
    'view_summary': 'عرض الملخص',
    'estimated_total': 'الإجمالي التقديري',
    'quotation_summary': 'ملخص عرض السعر',
    'subtotal_items_addons': 'الإجمالي (البنود والإضافات)',
    'profit_margin': 'هامش الربح',
    'discount': 'الخصم',
    'tax': 'الضريبة',
    'total_price': 'السعر الإجمالي',
    'internal_cost': 'التكلفة الداخلية',
    'client_context': 'العميل والمشروع',
    'assign_customer_project': 'تحديد العميل وتفاصيل المشروع',
    'system_topology': 'نوع النظام',
    'select_topology': 'اختر نوع النظام الشمسي لهذا العرض',
    'topology_selection': 'اختيار نوع النظام',
    'system_parameters': 'مواصفات النظام',
    'system_description': 'وصف النظام',
    'system_capacity_required': 'قدرة النظام *',
    'capacity_unit': 'وحدة القدرة',
    'quotation_date': 'تاريخ العرض',
    'valid_until': 'صالح حتى',
    'lifecycle_dates': 'تواريخ العرض',
    'bill_of_materials': 'قائمة المكونات',
    'required_components': 'المكونات المطلوبة لنظام',
    'add_custom_item': 'إضافة بند مخصص',
    'internal_pricing': 'التسعير الداخلي',
    'costs_margins_taxes': 'التكاليف، الهوامش والضرائب',
    'direct_costs_addons': 'التكاليف المباشرة والإضافات',
    'additional_materials': 'مواد إضافية',
    'transportation': 'النقل',
    'installation': 'التركيب',
    'other_cost': 'تكاليف أخرى',
    'pricing_logic': 'منطق التسعير',
    'document_content': 'محتوى المستند',
    'official_text_pdf': 'النصوص الرسمية لمستند الـ PDF',
    'document_drafting': 'صياغة المستند',
    'introduction': 'المقدمة',
    'general_terms': 'الشروط العامة',
    'terms_and_conditions': 'الشروط والأحكام',
    'payment_terms': 'شروط الدفع',
    'item_details': 'تفاصيل البند',
    'item_name_required': 'اسم البند *',
    'origin': 'المنشأ',
    'internal_notes_optional': 'ملاحظات داخلية (اختياري)',
    'product_component_catalog': 'كتالوج المنتجات والمكونات',
    'manual_item_no_catalog': 'بند يدوي - خارج الكتالوج',
    'select_customer_first': 'اختر العميل أولاً',
    'no_projects_for_customer': 'لا توجد مشاريع لهذا العميل',
    'loading_customers': 'جاري تحميل العملاء...',
    'failed_load_customers': 'فشل تحميل العملاء',
    'loading_projects': 'جاري تحميل المشاريع...',
    'failed_load_projects': 'فشل تحميل المشاريع',
    'customer_required': 'العميل مطلوب',
    'capacity_required': 'القدرة مطلوبة',
    'please_select_customer': 'يرجى اختيار عميل',
    'enter_valid_capacity': 'يرجى إدخال قدرة نظام صحيحة',
    'add_at_least_one_item': 'يرجى إضافة بند واحد على الأقل للعرض',
    'items_must_have_name': 'يجب أن يكون لجميع البنود اسم',
    'item_must_have_qty': 'يجب أن يكون له كمية أكبر من ٠',
    'margin_range_error': 'هامش الربح يجب أن يكون بين ٠ و ١٠٠٪',
    'tax_range_error': 'الضريبة يجب أن تكون بين ٠ و ١٠٠٪',
    'missing_required_categories': 'أصناف مطلوبة مفقودة',
    'quotation_created_success': 'تم إنشاء عرض السعر بنجاح',
    'quotation_updated_success': 'تم تحديث عرض السعر بنجاح',
    'failed_load_quotation': 'فشل تحميل عرض السعر',
    'quotation_not_found': 'عرض السعر غير موجود',
    'no_quotations_found': 'لم يتم العثور على عروض أسعار',
    'all_types': 'كل الأنواع',

    // --- Statuses & Channels ---
    'Draft': 'مسودة',
    'Pending': 'قيد المراجعة',
    'Approved': 'مقبول',
    'Sent': 'تم الإرسال',
    'Rejected': 'مرفوض',
    'Expired': 'منتهي',
    'In Progress': 'قيد التنفيذ',
    'Completed': 'مكتمل',
    'Cancelled': 'ملغي',
    'Facebook': 'فيسبوك',
    'WhatsApp': 'واتساب',
    'Website': 'الموقع الإلكتروني',
    'Referral': 'توصية / ترشيح',
    'Call': 'مكالمة هاتفية',
    'Walk-in': 'زيارة مباشرة',
    'Exhibition': 'معرض',
    'Other': 'أخرى',
    'Organic Lead': 'عميل مباشر (Organic)',
    'Won': 'تم التعاقد',
    'Lost': 'فقدت',
    'Negotiation': 'تفاوض',
    'Quotation Sent': 'تم إرسال العرض',
    'Contacted': 'تم التواصل',
    'Visited': 'تمت الزيارة',
    'New': 'جديد',
    'Deferred': 'مؤجل',
    'On-Grid': 'محطة On-Grid',
    'Off-Grid': 'محطة Off-Grid',
    'Solar Pump': 'طلمبة شمسية',

    // --- Governorates ---
    'Cairo': 'القاهرة',
    'Alexandria': 'الإسكندرية',
    'Giza': 'الجيزة',
    'Red Sea': 'البحر الأحمر',
    'South Sinai': 'جنوب سيناء',
    'North Sinai': 'شمال سيناء',
    'Port Said': 'بور سعيد',
    'Suez': 'السويس',
    'Luxor': 'الأقصر',
    'Aswan': 'أسوان',
    'Qena': 'قنا',
    'Sohag': 'سوهاج',
    'Assiut': 'أسيوط',
    'Minya': 'المنيا',
    'Beni Suef': 'بني سويف',
    'Fayoum': 'الفيوم',
    'Dakahlia': 'الدقهلية',
    'Sharqia': 'الشرقية',
    'Qalyubia': 'القليوبية',
    'Kafr El Sheikh': 'كفر الشيخ',
    'Gharbia': 'الغربية',
    'Monufia': 'المنوفية',
    'Beheira': 'البحيرة',
    'Ismailia': 'الإسماعيلية',
    'Damietta': 'دمياط',
    'Matrouh': 'مطروح',
    'New Valley': 'الوادي الجديد',

    // --- Batch 2 ---
    'all_channels': 'كل القنوات',
    'unknown_user': 'مستخدم غير معروف',
    'reset': 'إعادة تعيين',
    'filter': 'تصفية',
    'filter_customers': 'تصفية العملاء',
    'apply_filters': 'تطبيق الفلاتر',
    'interaction_tracking': 'تتبع التواصل',
    'first_contact': 'التواصل الأول',
    'final_contact': 'التواصل النهائي',
    'comment': 'تعليق',
    'whatsapp': 'واتساب',
    'email_item': 'بريد إلكتروني',
    'note': 'ملاحظة',
    'visit': 'زيارة',
    'filter_projects': 'تصفية المشاريع',
    'total_kw': 'إجمالي كيلوواط',
    'min': 'الأقل',
    'max': 'الأكثر',
    'active_only': 'النشط فقط',
    'add_user': 'إضافة مستخدم',
    'edit_user': 'تعديل مستخدم',
    'account_settings': 'إعدادات الحساب',
    'full_name': 'الاسم الكامل',
    'invalid_email': 'بريد إلكتروني غير صالح',
    'role': 'الدور',
    'select_role': 'اختر الدور',
    'new_password_label': 'كلمة مرور جديدة',
    'confirm_password_label': 'تأكيد كلمة المرور',
    'solar_panels': 'ألواح شمسية',
    'mounting_structure': 'هياكل تثبيت',
    'inverter': 'إنفرتر',
    'dc_cables': 'كابلات DC',
    'dc_combiner': 'صندوق تجميع DC',
    'cable_tray': 'حوامل كابلات',
    'grounding_system': 'نظام تأريض',
    'maintenance': 'صيانة',
    'batteries': 'بطاريات',
    'inverter_panel': 'لوحة إنفرتر',
    'cable_pipes': 'مواسير كابلات',
    'topology': 'نوع النظام',
    'no_users_found': 'لم يتم العثور على مستخدمين',
    'pcs': 'قطعة',
    'installation_item': 'التركيب',
    'transportation_item': 'النقل',
    'active': 'نشط',
    'disabled': 'معطل',
    'inactive': 'غير نشط',
    'history': 'سجل',
    'adjust': 'تعديل',
    'solar_invoice_desc': 'فاتورة مشروع طاقة شمسية',
    'select_gov': 'اختر المحافظة',
    'select_channel': 'اختر القناة',
    'select_status': 'اختر الحالة',
    'reset_password_for': 'إعادة تعيين كلمة المرور لـ ',
    'min_12_chars': '١٢ حرفاً على الأقل.',
    'passwords_no_match': 'كلمات المرور غير متطابقة.',
    'new_password': 'كلمة مرور جديدة',
    'confirm_password': 'تأكيد كلمة المرور',
    'basic_info': 'المعلومات الأساسية',
    'task': 'مهمة',
    'meeting': 'اجتماع',
    'follow_up': 'متابعة',
    'installation_event': 'تركيب',
    'events': 'فعاليات',
    'dates': 'التواريخ',
  };

  static String of(BuildContext context, String key, WidgetRef ref) {
    final locale = ref.watch(localeProvider);
    final strings = locale.languageCode == 'ar' ? _ar : _en;
    return strings[key] ?? key;
  }

  static String en(String key) => _en[key] ?? key;
}

extension LocalizedStrings on String? {
  String tr(WidgetRef ref) {
    if (this == null) return '';
    final locale = ref.watch(localeProvider);
    final strings = locale.languageCode == 'ar' ? AppStrings._ar : AppStrings._en;
    return strings[this!] ?? this!;
  }
}
